language: python
python:
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
addons:
  postgresql: "9.3"
script:
  - py.test
after_success:
  - "coveralls"
sudo: false
